export { default as ConfirmDialog } from './confirm-dialog'
export { default as CustomerDialog } from './customer'
export { default as MachineDialog } from './machine'
export { default as SiteDialog } from './site'
export { default as ContactDialog } from './contact'
