export const FETCH_ERROR = {
  FETCH_ERROR: 'Fetch-ERROR: ',
  GET_SECURITY_USERS_ERROR: 'Thunk-GET_SECURITY_USERS_ERROR: ',
  GET_SECURITY_USER_ERROR: 'Thunk-GET_SECURITY_USER_ERROR: ',
  GET_SIGN_IN_LOGS_ERROR: 'Thunk-GET_SIGN_IN_LOGS_ERROR: ',
  SET_SECURITY_PASSWORD_ERROR: 'Thunk-SET_SECURITY_PASSWORD_ERROR: ',
  SEND_USER_INVITE: 'Thunk-SEND_USER_INVITE: '
}

export const DEBUG = {
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR: ',
  ...FETCH_ERROR
}
